updates deploy workflow

diff --git a/.github/workflows/docker-deploy.yml b/.github/workflows/docker-deploy.yml
--- a/.github/workflows/docker-deploy.yml
+++ b/.github/workflows/docker-deploy.yml
@@ -1,4 +1,4 @@
-name: Build and Deploy to Docker Hub
+name: Build and Deploy to Docker Hub and GitHub Packages
 
 on:
   workflow_run:
@@ -13,54 +13,57 @@ jobs:
     outputs:
       success: ${{ steps.check_success.outputs.success }}
     steps:
-    - name: Check if previous workflows were successful
-      id: check_success
-      run: |
-        if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
-          echo "One or more of the required workflows failed."
-          echo "::set-output name=success::false"
-          exit 1
-        fi
-        echo "::set-output name=success::true"
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
+
   build-and-push:
     needs: check_previous_success
     if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
-    - name: Check out code
-      uses: actions/checkout@v3
+      - name: Check out code
+        uses: actions/checkout@v3
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_TOKEN }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
 
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v6
-      with:
-        push: true
-        tags: |
-          aaronzi/go-demo-api:${{ github.sha }}
-          aaronzi/go-demo-api:latest
-        platforms: linux/amd64,linux/arm64
+      - name: Log in to GitHub Packages
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    # Mirror the image to GitHub Packages
-    - name: Pull Docker Image from Docker Hub
-      run: docker pull aaronzi/go-demo-api:latest
+      - name: Prepare Docker Metadata
+        id: meta
+        uses: docker/metadata-action@v3
+        with:
+          images: |
+            aaronzi/go-demo-api
+            ghcr.io/${{ github.repository_owner }}/go-demo-api
+          tags: |
+            type=sha
+            type=ref,event=branch
+            type=semver,pattern={{version}}
 
-    - name: Tag the Image for GitHub Packages
-      run: docker tag aaronzi/go-demo-api:latest ghcr.io/${{ github.repository_owner }}/go-demo-api:latest
-
-    - name: Log in to GitHub Packages
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Push the Image to GitHub Packages
-      run: docker push ghcr.io/${{ github.repository_owner }}/go-demo-api:latest
+      - name: Build and Push Docker Image to Docker Hub and GitHub Packages
+        uses: docker/build-push-action@v6
+        with:
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          platforms: linux/amd64,linux/arm64
